spring.datasource.url=${SUPABASE_DB_URL:jdbc:postgresql://localhost:5432/fitoherb-v2}
# A senha e usuario serao herdados do application.properties usando as variaveis de ambiente ou sobrescritos aqui
# spring.datasource.username=${PostgresUsername}
# spring.datasource.password=${PostgresPassword}

# Nome do bucket GCS para o ambiente de producao
gcp.bucket.name=fitoherb-images-bucket
