spring.application.name=fitoherb-backend-v2

spring.datasource.url=jdbc:postgresql://localhost:5432/fitoherb_v2_test
spring.datasource.username=${PostgresUsername}
spring.datasource.password=${PostgresPassword}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=secret-key-para-testes-unitarios-e-integracao-123456

spring.mail.host=localhost
spring.mail.port=3025
spring.mail.username=test-user
spring.mail.password=test-pass

path.supplierImages=C:\\Users\\PC\\Documents\\FitoherbImages\\Tests\\Suppliers
path.productImages=C:\\Users\\PC\\Documents\\FitoherbImages\\Tests\\Products
path.categoryImages=C:\\Users\\PC\\Documents\\FitoherbImages\\Tests\\Categories

spring.jackson.date-format=dd-MM-yyyy
spring.jackson.time-zone=GMT-3

logging.level.root=WARN
logging.level.com.fitoherb=DEBUG