spring.application.name=fitoherb-backend-v2

spring.datasource.url=jdbc:postgresql://localhost:5432/fitoherb-v2
spring.datasource.username=${PostgresUsername}
spring.datasource.password=${PostgresPassword}

api.security.token.secret=${JWT_SECRET}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${mailSenderUsername}
spring.mail.password=${mailSenderPassword}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.servlet.multipart.max-file-size=10MB

spring.servlet.multipart.max-request-size=10MB

local.storage.path=C:/Users/PC/Documents/FitoherbImages

# GCP bucket e Supabase ficarao no application-prod.properties
# gcp.bucket.name=fitoherb-images-bucket

spring.jackson.date-format=dd-MM-yyyy
spring.jackson.time-zone=GMT-3

springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.persistAuthorization=true
springdoc.swagger-ui.docExpansion=none
