spring.datasource.url=${QA_DB_URL:jdbc:postgresql://localhost:5432/fitoherb-v2}
# A senha e usuario serao herdados do application.properties usando as variaveis de ambiente ou sobrescritos aqui
# spring.datasource.username=${QA_DB_USERNAME}
# spring.datasource.password=${QA_DB_PASSWORD}

# Nome do bucket GCS para o ambiente de QA (estamos usando o mesmo de prod por enquanto)
gcp.bucket.name=fitoherb-images-bucket

# Limite de conexoes do HikariCP para nao estourar o limite (pool_size: 15) do Supabase
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
