spring.application.name=fitoherb-backend-v2

spring.datasource.url=jdbc:postgresql://localhost:5432/fitoherb-v2
spring.datasource.username=${PostgresUsername}
spring.datasource.password=${PostgresPassword}

api.security.token.secret=${PostgresPassword}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


path.supplierImages=C:\\Users\\PC\\Documents\\FitoherbImages/Suppliers
path.productImages=C:\\Users\\PC\\Documents\\FitoherbImages/Products
path.categoryImages=C:\\Users\\PC\\Documents\\FitoherbImages/Categories

spring.jackson.date-format=dd-MM-yyyy
spring.jackson.time-zone=GMT-3

springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.persistAuthorization=true
springdoc.swagger-ui.docExpansion=none
