name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main
      - master

env:
  PROJECT_ID: fitoherb
  SERVICE_NAME: fitoherb-backend
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositorio
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Tornar o gradlew executavel
        run: chmod +x gradlew

      - name: Compilar o codigo Java (Gradle Build)
        run: ./gradlew build -x test

      - name: Autenticar no Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Configurar o Google Cloud CLI
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configurar o Docker para enviar imagens
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Criar Imagem Docker e Enviar pro GCP (Artifact Registry)
        run: |
          IMAGE_NAME="us-central1-docker.pkg.dev/$PROJECT_ID/fitoherb-repo/$SERVICE_NAME:${{ github.sha }}"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Publicar no Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE_NAME }}'
          region: '${{ env.REGION }}'
          image: 'us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/fitoherb-repo/${{ env.SERVICE_NAME }}:${{ github.sha }}'
          flags: '--allow-unauthenticated --port=8080'
          env_vars: |
            SPRING_PROFILES_ACTIVE=prod
            SPRING_DATASOURCE_URL=${{ secrets.PROD_DB_URL }}
            SPRING_DATASOURCE_USERNAME=${{ secrets.PROD_DB_USERNAME }}
            PostgresUsername=${{ secrets.PROD_DB_USERNAME }}
            SPRING_DATASOURCE_PASSWORD=${{ secrets.PROD_DB_PASSWORD }}
            PostgresPassword=${{ secrets.PROD_DB_PASSWORD }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            mailSenderUsername=${{ secrets.MAIL_USERNAME }}
            mailSenderPassword=${{ secrets.MAIL_PASSWORD }}
