name: Restore Supabase Database Backup

on:
  workflow_dispatch:

jobs:
  restore:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar arquivo de backup do workflow anterior
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: backup.yml
          name: fitoherb_backup
          path: .

      - name: Executar psql via Docker para restaurar
        env:
          PGPASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
          DB_URL: ${{ secrets.PROD_DB_URL }}
          DB_USERNAME: ${{ secrets.PROD_DB_USERNAME }}
        run: |
          # Extrai o host da URL JDBC
          HOST=$(echo $DB_URL | sed -E 's/jdbc:postgresql:\/\/([^:]+).*/\1/')
          
          echo "Restaurando no host: $HOST com usuario: $DB_USERNAME"
          
          docker run --rm -v ${{ github.workspace }}:/workspace -e PGPASSWORD="${PGPASSWORD}" postgres:17 psql -h $HOST -p 5432 -U "$DB_USERNAME" -d postgres -f /workspace/fitoherb_backup.sql
